destination: ./_site
server_port: 4000
pygments:    true
markdown:    rdiscount
permalink:   /:year/:month/:title
title: richardc - hardly moving
url:  http://richardc.unixbeard.net
author: Richard Clamp
